% Albert_darchicourt_Cisse   (2471152)
% Charles_Jobin_Fauvel       (1896074)

include "globals.mzn";

%-----------------------------------------------------------------------------%
% Données
%-----------------------------------------------------------------------------%

% Nombre d'acteurs et de rôles
int: n;
% Couleurs des costumes
enum costumes; 
% Costume démandé pour un rôle i (première dimension) par un acteur j (seconde dimension)
array[1..n,1..n] of costumes: choix_costume;

%-----------------------------------------------------------------------------%
% Variables de décisions
%-----------------------------------------------------------------------------%

% Variables de décision pour assigner un acteur à un rôle
array [1..n] of var 1..n: assignation_role;

%-----------------------------------------------------------------------------%
% Partie étudiant
%-----------------------------------------------------------------------------%

% Chaque acteur a un rôle différent (un seul et unique rôle par acteur)
constraint alldifferent(assignation_role);

% Chaque acteur doit avoir un costume différent
% Le costume de l'acteur i est choix_costume[assignation_role[i], i]
constraint alldifferent([choix_costume[assignation_role[i], i] | i in 1..n]);

% Deux acteurs voisins ne peuvent pas avoir des rôles adjacents
constraint forall(i in 1..n-1) (
    abs(assignation_role[i] - assignation_role[i+1]) != 1
);

solve satisfy;

%-----------------------------------------------------------------------------%

output	
  ["L'acteur " ++ format(i) ++ 
   " prendra le rôle " ++ format(fix(assignation_role[i])) ++ 
   " (costume " ++ format(choix_costume[fix(assignation_role[i]), i]) ++ ")" ++"\n" 
  | i in 1..n];